[workspace]
members = ["crates/*"]
#exclude = ["crates/local"]
#default-members = ["crates/internal"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
#strip = true
#panic = "abort"

#[workspace.dependencies]
